<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Candidats extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Educazad_model');
    }

    /*
     * Listing of tb_am_users
     */
    function index()
    {
        $data['all_candidats'] = $this->Educazad_model->get_multiple('tb_rm_candidats', array(), 'tb_rm_candidats.candidat_id','DESC');

        $data['_view'] = 'candidats/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_am_user
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nom_complet','Nom Complet','required');
        $this->form_validation->set_rules('sexe','sexe','required');
        $this->form_validation->set_rules('lieu_naissance','lieu_naissance','required');
        $this->form_validation->set_rules('date_naissance','date_naissance','required');
        $this->form_validation->set_rules('email','email','required|valid_email');
        $this->form_validation->set_rules('telephone','telephone','required');
        $this->form_validation->set_rules('niveau_etude','Grade','required');

        if($this->form_validation->run())
        {
            $current_datetime=date('Y-m-d H:i:s');
            $params = array(
                'nom_complet' => $this->input->post('nom_complet'),
                'sexe' => $this->input->post('sexe'),
                'email' => $this->input->post('email'),
                'lieu_naissance' => $this->input->post('lieu_naissance'),
                'date_naissance' => $this->input->post('date_naissance'),
                'telephone' => $this->input->post('telephone'),
                'date_ajout' =>  $current_datetime,
                'niveau_etude' => $this->input->post('niveau_etude'),
                'matricule' => $this->input->post('matricule'),
                'observation_candidat' => $this->input->post('observation_candidat'),
                'adresse' => $this->input->post('adresse'),
            );
            $this->Educazad_model->insert_data('tb_rm_candidats',$params);
            redirect('candidats/index');
        }
        else
        {
            $data['_view'] = 'candidats/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a tb_am_user
     */
    function edit($candidatID)
    {
        // check if the tb_am_user exists before trying to edit it
        //$data['candidat'] = $this->User_model->get_tb_am_user($id_asset);
        $data['candidat'] = $this->Educazad_model->get_one_row('tb_rm_candidats', array('candidat_id'=>$candidatID));

        if(isset($data['candidat']))
        {
            $this->form_validation->set_rules('nom_complet','Nom Complet','required');
            $this->form_validation->set_rules('sexe','sexe','required');
            $this->form_validation->set_rules('lieu_naissance','lieu_naissance','required');
            $this->form_validation->set_rules('date_naissance','date_naissance','required');
            $this->form_validation->set_rules('email','email','required|valid_email');
            $this->form_validation->set_rules('telephone','telephone','required');
            $this->form_validation->set_rules('niveau_etude','Grade','required');
            $this->form_validation->set_rules('matricule','Matricule','required');

            if($this->form_validation->run())
            {
                $current_datetime=date('Y-m-d H:i:s');
                $params = array(
                    'nom_complet' => $this->input->post('nom_complet'),
                    'sexe' => $this->input->post('sexe'),
                    'email' => $this->input->post('email'),
                    'lieu_naissance' => $this->input->post('lieu_naissance'),
                    'date_naissance' => $this->input->post('date_naissance'),
                    'telephone' => $this->input->post('telephone'),
                    'date_modif' =>  $current_datetime,
                    'niveau_etude' => $this->input->post('niveau_etude'),
                    'matricule' => $this->input->post('matricule'),
                    'observation_candidat' => $this->input->post('observation_candidat'),
                    'adresse' => $this->input->post('adresse'),
                );
                $this->Educazad_model->update_data('tb_rm_candidats',$params,  array('candidat_id'=>$candidatID));
                redirect('candidats/index');
            }
            else
            {
                $data['_view'] = ('candidats/edit');
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('Table non existant. ');
    }
}